//ContactUs 
export const CREATE_CONTACTUS = "CREATE_CONTACTUS"
export const CREATE_CONTACTUS_RED = "CREATE_CONTACTUS_RED"
export const GET_CONTACTUS = "GET_CONTACTUS"
export const GET_CONTACTUS_RED = "GET_CONTACTUS_RED"
export const UPDATE_CONTACTUS = "UPDATE_CONTACTUS"
export const UPDATE_CONTACTUS_RED = "UPDATE_CONTACTUS_RED"
export const DELETE_CONTACTUS = "DELETE_CONTACTUS"
export const DELETE_CONTACTUS_RED = "DELETE_CONTACTUS_RED"

// NEWSLETTER
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED = "CREATE_NEWSLETTER_RED"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED"
export const UPDATE_NEWSLETTER = "UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_RED = "UPDATE_NEWSLETTER_RED"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED"
